### ISSUE TITLE
vulkan shaders

### ISSUE THREAD

**Issue by BETLOG** [shudnal/LongshipUpgrades#2]
Not sure if LongshipUpgrades issue or vanilla boat asset issue. Happened after being bitten by a shark (Marlthon-SeaAnimals).
Possibly not something you can fix, I just figured i'd point it out.

![2024-11-16--22-36-16_betlogbeast_1920x1080+0+0](https://github.com/user-attachments/assets/a89dbad0-b9bc-48de-8e91-26d120046c53)

**Comment by shudnal** [comment]
It should be better in the next version but when will it come live I can't say. Currently game restart should help.
